// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/child.vue')['default']
    ChildSetup: typeof import('./src/components/child-setup.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}

export {}
